package GuessOutput;

import java.io.IOException;

public class Programm4 {

	public static void main(String[] args) {

		// This code results in a compile time error.
		//The exception IOException is already caught by the alternative Exception.
			   
//		   		try {
//		   			throw new IOException("Hello");
//		   		} catch(IOException | Exception e) {
//		   			System.out.println(e.getMessage());
//		   		}
		   		
	}

}
